### PR TITLE
Feature/frontend UI 

### PR DESCRIPTION
**Pull request by bensgilbert**
Consistent (mostly) UI, check it out!

### CODE REVIEW

**Comment by eklipse18** [comment]
Uh oh. seems like you also committed node_modules. That's usually a bad idea since node_modules is usually very large and has lots of files. It's sort of like committing a virtual environment in python.

**Review by kappq — COMMENTED** [review]
I can enter a room with an empty code. I feel like this should be handled in the front end rather than in the back end.

**Comment by kappq** [comment]
I think that, when the user joins a room, it should be redirected to another page, rather than dynamically changing the UI. This could come in handy when we have multiple rooms so that the user can just share the link to it.

**Comment by eklipse18** [comment]
Hm... how would that work though? We're not using fastapi to build webpages, just serve them, so when we build the frontend there is no way for it to know the dynamic content right? Also the point of using room codes is so that the user shares the code of the room instead of the room link right?

**Comment by eklipse18** [comment]
As I don't think we're using this branch anymore, I'm closing the PR.

**Pull request closed without merging**
